services:
  Contexts.Backoffice.Backend.product.reviews.config.application.increment.ProductReviewsConfigReviewsIncrementer:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews-config/application/increment/ProductReviewsConfigReviewsIncrementer
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.config.domain.ProductReviewsConfigRepository"]
  Contexts.Backoffice.Backend.product.reviews.config.application.increment.negative.reviews.ProductReviewsConfigNegativeReviewsIncrementer:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews-config/application/increment-negative-reviews/ProductReviewsConfigNegativeReviewsIncrementer
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.config.domain.ProductReviewsConfigRepository"]
  Contexts.Backoffice.Backend.product.reviews.config.application.create.ProductReviewsConfigCreator:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews-config/application/create/ProductReviewsConfigCreator
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.config.domain.ProductReviewsConfigRepository"]
  Contexts.Backoffice.Backend.product.reviews.config.update.ProductReviewsConfigUpdater:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews-config/application/update/ProductReviewsConfigUpdater
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.config.domain.ProductReviewsConfigRepository"]
  Contexts.Backoffice.Backend.product.reviews.config.update.ConfigureProductReviewsConfigCommandHandler:
    class: ../../../../../../../../../contexts/backoffice/backend/product-reviews-config/application/update/ConfigureProductReviewsConfigCommandHandler
    arguments: ["@Contexts.Backoffice.Backend.product.reviews.config.update.ProductReviewsConfigUpdater"]
