services:
  Backoffice.RabbitMqConnection:
    class: ../../../../../../shared/infrastructure/event/rabbitmq/RabbitMqConnection
    arguments: []
  Backoffice.DomainEventFailover:
    class: ../../../../../../shared/infrastructure/event/failover/DomainEventFailover
    arguments: ["@Backoffice.ConnectionManager"]
  Backoffice.EventBus:
    class: ../../../../../../shared/infrastructure/event/rabbitmq/RabbitMqEventBus
    arguments: ["@Backoffice.RabbitMqConnection", "@Backoffice.DomainEventFailover"]
  Apps.Backoffice.Backend.ExpressHttpServer:
    class: ../../../ExpressHttpServer
    arguments:
      [
        "@Apps.Backoffice.Backend.RouteValidator",
        "@Apps.Backoffice.Backend.RouteHandlers",
      ]
  Apps.Backoffice.Backend.BackofficeBackendApp:
    class: ../../../BackofficeBackendApp
    arguments: ["@Apps.Backoffice.Backend.ExpressHttpServer"]

