name: Develop Branch Actions
run-name: CI/CD GitHub actions on develop branch 🚀
on: [push]
jobs:
  Develop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check node version
        run: |
          node -v
