services:
  Contexts.Backoffice.Backend.product.sentiment.classifier.domain.SentimentClassifier:
    class: ../../../../../../../../../contexts/backoffice/backend/review-sentiment-classifier/infrastructure/Qwen314BSentimentClassifier
    arguments: []
  Contexts.Backoffice.Backend.product.sentiment.classifier.application.create.ReviewContentSentimentClassifier:
    class: ../../../../../../../../../contexts/backoffice/backend/review-sentiment-classifier/application/ReviewContentSentimentClassifier
    arguments: ["@Contexts.Backoffice.Backend.product.sentiment.classifier.domain.SentimentClassifier", "@Backoffice.EventBus"]
  Contexts.Backoffice.Backend.product.sentiment.classifier.application.create.LabelSentimentFromReviewContentCommandHandler:
    class: ../../../../../../../../../contexts/backoffice/backend/review-sentiment-classifier/application/LabelSentimentFromReviewContentCommandHandler
    arguments: ["@Contexts.Backoffice.Backend.product.sentiment.classifier.application.create.ReviewContentSentimentClassifier"]